:version: 26.x
:secondaryver: 1.20.1
:factionmgr: cocainesnake
:townmgr: onogai
:jayson: jayson.json

= DMU {version}/{secondaryver} Information

This contains all relevant information about the changes made in the update from 1.16.5 to the {version} or {secondaryver} versions of DMU.

Note that everything here is subject to change and will be updated accordingly.

== General

=== Will the world be reset?
[%collapsible]
====
Yes; not only are we switching modloaders for {version}, but it's also a major change in versions for both {version} and {secondaryver}.

With the changes in code Mojang has made between 1.16.5 and {version} as well as {secondaryver}, there's a slim chance even a vanilla server could keep the same world.

On the rare chance it would work, many new vanilla features would be unavailable. As our aim is to tie the mod's progression into a lot of the current aspects of Minecraft itself, an old world ported up would result in some content being unavailable as well.

"Just increase the world border size" - as of writing, the world files for the 2026 era of 1.16.5 DMU are over 100GB, with the 2024 world files being 245GB. +
Storage is expensive.

Since {version} Dalek Mod is a rewrite not a port, many blocks will be added and removed, alongside many new and removed systems.

Pretty much the same goes for {secondaryver} - although this version _is_ a port, many systems will be added or existing ones changed, blocks updated, removed or added

We will not be carrying *any* DM-related content over from previous versions of DMU - whether it's your interior, base, etc
====

== Faction changes

Players can only be a member of 2 factions at once and can only own 1. +
Players who own a faction can still join 1 other faction.

=== Registration
[%collapsible]
====
In order for staff to recognise a faction on DMU, it will need to be registered. +
This is a mandatory requirement with no exceptions - more information in the *_Staff Involvement_* tab

The initial creation of a faction can only be done by server admins. +
However faction owners, or anyone with role perms, can later change certain aspects.

To get your faction created and registered, message `{factionmgr}` with the following:

- The name of your faction

- The Minecraft username of the owner

Keep in mind that the faction requirements are still in place.
====

=== Capes
[%collapsible]
====
After getting your faction registered, you'll have the option of adding custom capes.

These capes will be added to specifically DMU to avoid cluttering the main mod.

The faction owner, or anyone with perms, will then be able to give these capes to members.

To get a cape added, message `{jayson}` with the following:

* The name of your faction

* The identifier

** For e.g. `unit:cape_one`

* Your custom cape texture

** You can get the default texture here: https://jaysonjson.github.io/DMU1.2x/default_cape.png +
====

=== Roles
[%collapsible]
====
With the new factions system, we've added in-faction roles that allow certain members more privileges than others.

Note that the faction owner will not (and cannot) have a role, but will have all permissions.

The permissions these roles can have are:

* `CHANGE_NAME` - Can change the factions name

* `CHANGE_AGGRESSION` - Can change the factions aggression stance

* `INVITE_MEMBERS` - Can invite other players to the faction

* `KICK_MEMBERS` - Can kick members from the faction

* `MANAGE_ROLES` - Can set another members role, alongside update permissions for it

* `ASSIGN_ROLES` - Can change a members role

* `ASSIGN_CAPES` - Can give members access to any capes the faction may have

Members can only target roles/members lower than their current role.
====

=== Staff Involvement
[%collapsible]
====
As mentioned in the *_Registration_* tab, factions _must_ be registered with staff. +
Failure to do so will result in a warning, and if still unregistered, the faction owner and possibly members of that faction, will be banned.

This, sadly, is the result of a prior faction, of which throughout its entire lifespan, consistently caused issues. +
Because of this, we were forced to implement proper rules and regulations before another similar faction shows up.

However, this means that *all factions* must abide by these rules, and similarly, they *must* be enforced.

Factions based on groups from Doctor Who itself _must_ adhere to stricter rules; the faction manager *must*:

- Have full viewing access to the faction, including any related Discord servers.
- Have the ability to forcefully remove players from the faction, despite their rank or position within the faction.
* _In extreme cases, this can include the faction owner._

Note that *no other members of staff* can demand things such as special permissions, privileges, or positions of power within your faction. +
If a member of staff tries demanding such things, report them immediately to the head of staff and/or faction manager.
====

== Town changes

There is no limit as to how many towns a player can be a member of.

=== Registration
[%collapsible]
====
Similarly to factions, towns can also be registered on DMU.

After getting registered, you will:

* Have a global TARDIS warp, which can be accessed via the planned global-warp-list system

** You will need to designate these positions and ensure the town has enough, otherwise players will be unable to land

* Have a designated town area, which can be appropriately increased by `{townmgr}`

* Have town ranks with configurable permissions (see *_Ranks_*)

* Have town capes, if the requirements are met

The town requirements are still in place.
====
=== Ranks
[%collapsible]
====
Much like factions, towns will have roles.

These roles can be granted different permissions, such as:

* `BREAK_BLOCKS`/`PLACE_BLOCKS`/`INTERACT_BLOCKS` - Can break, place, or interact with blocks in the towns given area

* `MANAGE_ROLES` - Can create other roles, and manage their permissions

* `ASSIGN_ROLES` - Can give members town roles

* `ASSIGN_CAPES` - Can give a player access to any capes the town may have

* `KICK_MEMBERS` - Can remove players from the town

* `BAN_MEMBERS` - Can ban members from the town, stopping them from entering the town area

* `ACCEPT_JOIN_REQUESTS` - Can accept a users request to join the town

Similarly to factions, the owner will not have a role but will have all permissions.

Members can only target roles/members lower than their current role.
====
=== Banned players
[%collapsible]
====
Banned players are not allowed to enter the town area, nor interact with any blocks within it.

Members with the `BAN_PLAYERS` permission can ban/unban players from the town.
====
=== Staff Involvement
[%collapsible]
====
The regulations aren't as strict for towns as they are factions - towns must only register if they want to be integrated into the town system, which provides a proper permission system (see *_Ranks_*), or the town warps.
====

== Ranks changes

Bold formatting within ranks prefixes has been removed.

It will automatically be removed from any requests made by `/prefix`.

=== Custom ranks
[%collapsible]
====
With our new database, we've added the ability to set a prefix that will display in the playerlist.

These prefixes are limited to 5 characters, excluding formatting and square brackets.

Hex formatting is also supported by both chat and tablist prefixes.

To get a tab prefix, you can either:

* Use the `/prefix` command

** You will need to wait for staff to accept it. Once they do, you'll have to wait a month before changing it again

*** If you have submitted a prefix change request but it has not yet been accepted, you can submit another one, and it'll override your previous request.

** This command can also change your chat prefix

* Message `{jayson}` with your current rank and what you'd like the prefix to be
====
== Chat Changes
=== Formatting
[%collapsible]
====
We've added the ability to use hex colour codes in chat.

This can be done by typing `<#000000>` in chat, replacing `#000000` with the hex colour of your choice.

By using `<#000000:#FFFFFF>`, a gradient will be applied to the rest of the message.

`<endg>` will end the gradient.

These will not play nicely with the deprecated `&` (`§`) formatting character as they are two vastly different systems

_You will still need chat formatting permissions to use this._
====
=== Variables
[%collapsible]
====
You can now use variables in chat to send certain information.

This currently includes the following:

- `<$hand>`
 * Will display your mainhand item in chat, including the tooltip

- `<$pos/position>`
 * Will display `[position]` in chat, letting users who hover over it see your blockpos and dimension.
====
